# GCP Storage Bucket Terraform Configuration
# Auto-generated by Backstage IDP

terraform {
  required_version = ">= 1.0.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.0.0"
    }
  }

  # Remote state configuration
  # For the monorepo, use a unique prefix for each bucket:
  # backend "gcs" {
  #   bucket = "your-terraform-state-bucket"
  #   prefix = "terraform/state/backstage-demo-gcp-bucket-00"
  # }
}

provider "google" {
  project = var.project_id
  region  = var.location
}

# Use the centralized module from the monorepo root
module "gcp_bucket" {
  source = "../../../modules/gcp-bucket"

  bucket_name   = var.bucket_name
  project_id    = var.project_id
  location      = var.location
  storage_class = var.storage_class
  environment   = var.environment
  
  description   = ""
}
