# GCP Storage Bucket Terraform Configuration
# Auto-generated by Backstage IDP

terraform {
  required_version = ">= 1.0.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.0.0"
    }
  }

  # Remote state configuration
  # For the monorepo, use a unique prefix for each bucket:
  # backend "gcs" {
  #   bucket = "your-terraform-state-bucket"
  #   prefix = "terraform/state/backstage-demo-gcp-bucket0000"
  # }
}

provider "google" {
  project = var.project_id
  region  = var.location
}

# Create the GCS bucket with best practices
resource "google_storage_bucket" "bucket" {
  name     = var.bucket_name
  project  = var.project_id
  location = var.location

  # Use uniform bucket-level access (recommended)
  uniform_bucket_level_access = true

  # Storage class
  storage_class = var.storage_class

  # Versioning for data protection
  versioning {
    enabled = true
  }

  # Lifecycle rules for cost optimization
  lifecycle_rule {
    action {
      type = "Delete"
    }
    condition {
      age                = 365
      num_newer_versions = 5
      with_state         = "ARCHIVED"
    }
  }

  # Soft delete policy for accidental deletion protection
  soft_delete_policy {
    retention_duration_seconds = 604800 # 7 days
  }

  # Labels for cost allocation and organization
  labels = {
    managed_by  = "terraform"
    created_by  = "backstage"
    environment = var.environment
    bucket_name = var.bucket_name
  }

  # Prevent accidental deletion
  force_destroy = false
}
